### PR TITLE
fix for mpc detection

### PR DESCRIPTION
**Pull request by dawidd6**
In my case your `if pgrep "mpd" >/dev/null 2>&1` is not working because i'm using mpd on server and mpc on my laptop, so i don't have mpd on it and `pgrep` is failing. I think it is better to search for mpc than for mpd in this `if`

### CODE REVIEW

**Comment by dylanaraps** [comment]
Hm, `mpc` isn't always running though is it?

**Comment by dylanaraps** [comment]
We could do `if pgrep "mpd|mpc" >/dev/null 2>&1` which should work right?

**Comment by dawidd6** [comment]
Unfortunelly pgrep is not working for mpc, so i've done this with `hash`

**Comment by dawidd6** [comment]
But mpd is not optional dependency for neofetch and mpc is

**Comment by dylanaraps** [comment]
Well we're using `mpc` to talk to `mpd` so it's implied that you need both installed. Is there a way to check that you're connected to mpd?

**Comment by dawidd6** [comment]
Yes, simply type `mpc` and output is saying under condition if you have MPD_HOST variable exported

**Comment by dylanaraps** [comment]
Awesome, I'll add this tomorrow! (I'm not on my linux pc atm.)

**Comment by dawidd6** [comment]
Damn, i see that my next commit has automatic apperared here.

okay, so i've added detection of charging status for single battery

zrzut ekranu z 2016-03-20 13-01-18

**Comment by dylanaraps** [comment]
Create a new branch for the battery stuff and make it so that it only shows status when the value is `Charging`. 

We also need to get it working when using multiple batteries!

**Comment by dawidd6** [comment]
Man, i have no idea how can i remove commit from this PR

**Comment by dylanaraps** [comment]
You can start over and instead work in two seperate branches.

**Comment by dawidd6** [comment]
OK, done. Created new branch and deleted commit from master :+1:

**Comment by dylanaraps** [comment]
I'll take a look at this tonight, I'm swamped with homework.

**Comment by dylanaraps** [comment]
I did some testing and changing the line to this should work and is much simpler!:

```sh
if mpc version >/dev/null 2>&1; then
```

**Comment by dylanaraps** [comment]
Thanks mate!

**Pull request merged**
