### PR TITLE
song: add album for some players

### PR DESCRIPTION
**Pull request by mstraube**
## Description
Add album support for most of the remaining players in the TODO list of #837

## Features
pogo
exaile
quodlibet
pragha
amarok
deadbeef
qmmp
xmms2d
mocp
rhythmbox
banshee
mpd

### CODE REVIEW

**Comment by mstraube** [comment]
Added a fix for cmus. Album was `albumartist` instead of `album`.

**Comment by iandrewt** [comment]
Wow I forgot about this feature. Is this ready to merge into song-album?

**Comment by dylanaraps** [comment]
Can this be re-submitted to merge into @iandrewt's branch instead of a new branch in Master?

**Comment by dylanaraps** [comment]
I'll work on some code to detect empty output and also push to @iandrewt's branch.

**Comment by iandrewt** [comment]
It's already going to song-album, I don't really use my own fork since I've been a collaborator, the branch is in this repo.

**Comment by iandrewt** [comment]
You can push your changes directly to dylanaraps:song-album if you want @dylanaraps

**Comment by mstraube** [comment]
> Wow I forgot about this feature. Is this ready to merge into song-album?

Yes, I think so. :)

**Pull request merged**
