### PR TITLE
add macOS High Sierra support

### PR DESCRIPTION
**Pull request by yslgirl**
Don't know if this is worth a pull request, but I added High Sierra support since it's releasing soon.

### CODE REVIEW

**Comment by konimex** [comment]
IMO, this should be on-hold until after the actual release of High Sierra. However, this PR shouldn't be closed.

**Comment by konimex** [comment]
Merged to master. Thanks for the PR.

**Comment by Nifled** [comment]
For some reason it's not showing the actual 'High Sierra' label on `OS`. Isn't that supposed to show?

**Comment by yslgirl** [comment]
@Nifled It looks to be showing for me. Did `neofetch` correctly display versions before High Sierra before you updated?
screen shot 2017-11-09 at 12 22 49 am

**Pull request merged**
