### PR TITLE
Update Android ascii

### PR DESCRIPTION
**Pull request by TsundereBug**
This is so it looks more uniform with the other arts.

## Description

Make the Android art look uniform with distros like Arch, Debian, Fedora, and Ubuntu

## Features

Revamp of Android art

### CODE REVIEW

**Comment by TsundereBug** [comment]
Demonstration of new look

**Comment by TsundereBug** [comment]
Demonstration of `neofetch`

**Comment by dylanaraps** [comment]
I know the current android ascii art doesn't match the others but it's tiny and looks good. We've attempted to change the android ascii twice now and the results weren't better than the blocky ascii.

If you can make this ascii a little be smaller while keeping it readable I'll merge this.

**Comment by TsundereBug** [comment]
Made slightly smaller. Will get screenshot in a few mins.

**Comment by TsundereBug** [comment]
Screenshot from SSH

Screenshot from Device

**Comment by dylanaraps** [comment]
LGTM :+1:

Thanks!

**Pull request merged**
