### PR TITLE
Add expidusos

### PR DESCRIPTION
**Pull request by RossComputerGuy**
## Description

Adds in ExpidusOS Alpha release logo

## Features
* Adds ExpidusOS logo

## TODO
* Resize logo
* Fix colors

### CODE REVIEW

**Comment by bgkillas** [comment]
maybe add color

**Comment by bgkillas** [comment]
btw as you can see here you made it wrong there should not be those dots in the front paste bin is how to fix https://imgur.com/a/IzNUFML https://pastebin.com/bvqxzD1J just like you know set it to white if you dont wanna add color

**Comment by RossComputerGuy** [comment]
@ctaetcsh did the conversion, whatever he used must've not worked correctly

**Comment by bgkillas** [comment]
nah he did it fine just cuz neofetch or something

**Comment by dylanaraps** [comment]
The ASCII is far too large. Look at the sizing of the other logos as a reference.

**Comment by ctaetcsh** [comment]
Thanks for letting me know, i'll take a look and resize it and send it along to @RossComputerGuy

**Comment by ctaetcsh** [comment]
I have left the ExpidusOS project and will not be returning.

**Pull request closed without merging**
