### PR TITLE
The Fedora logo needed some love

### PR DESCRIPTION
**Pull request by bluedaze**
I just updated ascii art to make it look more clean.

## Description

Only fill in the fields below if relevant.

### CODE REVIEW

**Comment by bluedaze** [comment]
If anyone wants to see a before and after here is an image.

https://i.imgur.com/Txo7XCA.png

**Comment by bluedaze** [comment]
Also I'm pretty new to this (literally the first time I pushed code to anything), so if anyone could let me know why Travis CI is failing I'd be grateful.

**Comment by arisinfenix** [comment]
Looking at the Travis log at https://travis-ci.com/github/dylanaraps/neofetch/jobs/359578721 there is a line too long.
```
$ if grep '.\{102\}' neofetch; then (exit 1); else (exit 0); fi
                                            'off', 'sixel', 'pot', 'pixterm', 'termpix', 'tycat', 'w3m')"
            "--ascii" | "--caca" | "--chafa" | "--jp2a" | "--iterm2" | "--off" | "--pot" | "--pixterm" |\
The command "if grep '.\{102\}' neofetch; then (exit 1); else (exit 0); fi" exited with 1.
```
But it is not from this PR. ;)

**Comment by bluedaze** [comment]
> Looking at the Travis log at https://travis-ci.com/github/dylanaraps/neofetch/jobs/359578721 there is a line too long.
> 
> ```
> $ if grep '.\{102\}' neofetch; then (exit 1); else (exit 0); fi
>                                             'off', 'sixel', 'pot', 'pixterm', 'termpix', 'tycat', 'w3m')"
>             "--ascii" | "--caca" | "--chafa" | "--jp2a" | "--iterm2" | "--off" | "--pot" | "--pixterm" |\
> The command "if grep '.\{102\}' neofetch; then (exit 1); else (exit 0); fi" exited with 1.
> ```
> 
> But it is not from this PR. ;)

This is a small change, so I was wondering if there is some sort of review process for pull requests or if there was a timeline for when this will be merged. 

It's been over a week, and I don't really know the process for how these things go. I looked for contributer guidelines but I couldn't find any.

**Pull request closed without merging**
