### PR TITLE
remove SC2010 ShellCheck exception

### PR DESCRIPTION
**Pull request by stevestock**
title says it all.  If you merge this, you may also want to [update the wiki](https://github.com/dylanaraps/neofetch/wiki/Shellcheck-Exclusions#sc2010)

### CODE REVIEW

**Comment by dylanaraps** [comment]
There's more than one instance of SC2010. Also `find` should be able to count the files too.

**Comment by stevestock** [comment]
It doesn't look like there are other instances of [SC2010](https://github.com/koalaman/shellcheck/wiki/SC2010).
In fact, [travis ran clean without the SC2010 exclusion](https://travis-ci.org/dylanaraps/neofetch/jobs/386844928#L446), by just removing the one instance mentioned in the [wiki](https://github.com/dylanaraps/neofetch/wiki/Shellcheck-Exclusions#sc2010)

And I did some searching and don't think that [find](https://linux.die.net/man/1/find) can count.  Please point me in the right direction if you think/know otherwise.

**Comment by dylanaraps** [comment]
My bad.

We can probably do something like this which is even faster.

```sh
for _ in "${1:-$HOME}"/*; do ((packages+=1)); done
```

**Comment by dylanaraps** [comment]
See #1015

**Comment by stevestock** [comment]
instead of replacement, it looks like the code was removed entirely in ffcf82d10d4e6c610e8e67c8570e5650be987d65.  Number of packages has reduced significantly vs previous revisions of neofetch and screenfetch. It looks like many other changes were made to reduce lint errors, but the travis.yml file still has not been updated.  Let me know if you'd like any help

**Comment by iandrewt** [comment]
ffcf82d was done because binaries that matched that criteria actually weren't from packages at all, they were just binaries placed there from other applications like VirtualBox.

**Comment by dylanaraps** [comment]
Good catch on the travis file.

**Comment by stevestock** [comment]
@dylanaraps want me to fix, or you already got it?

**Comment by dylanaraps** [comment]
Done it, thanks for the offer though.

**Comment by stevestock** [comment]
no problem.  Don't forget the [wiki](https://github.com/dylanaraps/neofetch/wiki/Shellcheck-Exclusions) too

**Comment by dylanaraps** [comment]
That'll happen after a release is made :)

**Comment by stevestock** [comment]
oh ok, got it

**Pull request closed without merging**
