### PR TITLE
Add Kali linux small logo

### PR DESCRIPTION
**Pull request by tkr-sh**
## Description
Added a small logo for Kali Linux
Source of the image inspiration: https://files.cults3d.com/uploaders/13889723/illustration-file/88f914f9-4ec0-4d0c-8ebb-5edc51f4b3cd/kali_linux.jpg

## Feature
Small logo for Kali Linux

### CODE REVIEW

**Review by hykilpikonna — APPROVED** [review]

**Comment by hykilpikonna** [comment]
Looks good

image

**Comment by hykilpikonna** [comment]
Thank you for your contribution! 

This PR is [merged into hyfetch](https://github.com/hykilpikonna/hyfetch/commit/b2b51fa6) since this repo (dylanaraps/neofetch) seems no longer maintained.

[HyFetch](https://github.com/hykilpikonna/hyfetch) is a fork of neofetch with LGBTQ pride flags, but the repo also maintains an updated version of the original neofetch, addressing many pull requests that are not merged in the original repo.

Read the ["Running Updated Original Neofetch" section](https://github.com/hykilpikonna/hyfetch#running-updated-original-neofetch) for more info!

**Comment by tkr-sh** [comment]
@hykilpikonna Thanks ! :D

**Comment by sauravsagarm** [comment]
Hii

**Pull request closed without merging**
