### PR TITLE
added ability to shorten cpu output

### PR DESCRIPTION
**Pull request by iandrewt**
usage: --cpu_shorthand (name, model, name_model, speed)
also edited config file to suit

addresses #130
documentation updates to come

### CODE REVIEW

**Comment by dylanaraps** [comment]
Wow, thanks for the PR.

I'll do some testing before merging this. :)

**Comment by iandrewt** [comment]
I've only tested on OS X, so Intel CPUs should work fine (unless output is different on other OSes?)

**Comment by iandrewt** [comment]
That's great! It just cuts the string at the dash and/or the @ depending on what option is chosen, so as long as the output is always in that format it should work fine

**Comment by iandrewt** [comment]
Based on the screenshots in `README.md`, Windows might have an issue as it doesn't have a dash between the "i5" and "760".

**Comment by dylanaraps** [comment]
The only issue I've found is that some CPUs don't have a `-` character in their name causing some of the shorthand options to not work. Here's an example:

```sh
# Add this just before the new shorthand case statement
cpu="Intel Core2 Duo T7500 @ 2.2GHz"

```

Here's another idea for the shorthand options which would work consistently. 

```sh
# Hide the speed
--cpu_shorthand name 

# Hide the brand 
# (Intel, AMD) 
# Output: i7 2600 @ 2.2GHz
--cpu_shorthand on

# Hide the speed and the brand name
# Output: i7 2600
--cpu_shorthand tiny
```

What do you think?

(I was typing this out before your latest comment :P)

**Comment by dylanaraps** [comment]
Here's an example that works on all the cpus I've tried.

```sh
    case "$cpu_shorthand" in
        "name")
            cpu=${cpu/@*}
        ;;

        "speed")
            cpu=${cpu#*@ }
        ;;

        "on")
            cpu=${cpu/Intel }
            cpu=${cpu/Core }
            cpu=${cpu/AMD }
        ;;

        "tiny")
            cpu=${cpu/Intel }
            cpu=${cpu/Core }
            cpu=${cpu/AMD }
            cpu=${cpu/@*}
        ;;
    esac
```

**Comment by dylanaraps** [comment]
I edited the case statement after I commented to remove the duplicate block between `on` and `tiny`, I also added another line to remove `CoreX Duo`. Once you make these changes I'll merge this. :)

**Comment by iandrewt** [comment]
Done! Works great with the original string `Intel Core i5-3210M @ 2.5GHz` and the Core2 Duo string too

**Comment by dylanaraps** [comment]
Thanks for the PR!

**Pull request merged**
