### PR TITLE
Fix song_shorthand, use dbus for audacious

### PR DESCRIPTION
**Pull request by mstraube**
## Description

- Fix typo in comparsion
- Use `get_song_dbus` for audacious since audtool returns `Artist - Album - Title`
- Don't print if `$song` is emtpy and `song_shorthand` is on (#638)

### CODE REVIEW

**Comment by dylanaraps** [comment]
LGTM :+1:

**Comment by dylanaraps** [comment]
Want me to merge this or do you want to wait for @IAmNotImportant's response?

**Comment by mstraube** [comment]
From my side you can merge it.

**Comment by dylanaraps** [comment]
Thanks!

**Pull request merged**
