### PR TITLE
Term Font: Add support for Pantheon Terminal

### PR DESCRIPTION
**Pull request by mstraube**
Adds font detection for Pantheon Terminal.

Tested on Arch and Elementary OS.

### CODE REVIEW

**Comment by mstraube** [comment]
Maybe change `[[ "$term_font" == "''" ]]` to `[[ "${term_font//\'}" ]]` ?

**Comment by mstraube** [comment]
Ah, it must be `[[ -z "${term_font//\'}" ]]`

What about `term_font="$(trim_quotes "$term_font")"`,
would you prefer to change it also to `term_font="${term_font//\'}"` ?

**Comment by dylanaraps** [comment]
LGTM :+1:

Is this ready to merge?

**Comment by mstraube** [comment]
yep

**Comment by dylanaraps** [comment]
Thanks :+1:

**Pull request merged**
