### PR TITLE
added obrevenge and archlabs ascii art for compatiblity for both new distros

### PR DESCRIPTION
**Pull request by obrevenge**
## Description

This will allow for compatibility for OBRevenge OS and ARCHlabs, both new Arch based distros.

### CODE REVIEW

**Comment by dylanaraps** [comment]
Remove all leading and trailing whitespace.

**Comment by dylanaraps** [comment]
You need to also add the distros to `get_distro_colors()`.

**Comment by dylanaraps** [comment]
The archlabs art is also missing `${c1}` and any other colors it needs.

**Comment by obrevenge** [comment]
I have made commits with the needed fixes, including removing whitespace, adding ${c1} to archlabs, and adding both to get_disro_colors().

**Comment by dylanaraps** [comment]
Thanks for the PR :+1:.

Sorry for the delay. :~

**Pull request merged**
