### PR TITLE
battery: fix battery detection on Windows

### PR DESCRIPTION
**Pull request by matoro**
## Description

Only fill in the fields below if relevant.

### CODE REVIEW

**Comment by dylanaraps** [comment]
Neofetch does a check to see if the data exists before printing it anyway.

**Comment by matoro** [comment]
@dylanaraps Well it does not seem to be working.  On Win7 Enterprise under MSYS2 it shows only a percent sign in the battery field.  Can provide logs as necessary.

**Comment by dylanaraps** [comment]
Did you copy paste my code from my above comment? I wrote it from my phone so it uses Unicode quotes. 

Rewrite it and I can merge. :P

**Comment by dylanaraps** [comment]
Thanks :+1:

**Pull request merged**
