### PR TITLE
Fix CPU usage on BSDs

### PR DESCRIPTION
**Pull request by tudurom**
This should work on all BSDs.

See #258.

### CODE REVIEW

**Comment by dylanaraps** [comment]
I'm going to look into adding a more OS specific version of the CPU Usage.

**Comment by tudurom** [comment]
what's wrong with this one?

**Comment by tudurom** [comment]
oh i put the line in the wrong spot.

**Comment by dylanaraps** [comment]
I'm not happy with using iostat to get the cpu usage.

It isn't installed by default in a lot of distros and iirc there's no version of iostat for CYGWIN.

I want to find a more universal solution if possible.

**Comment by tudurom** [comment]
i wanted initially to add that only for the BSDs. iostat is installed on all BSD operating systems

**Comment by dylanaraps** [comment]
The problem is that this PR adds it for all operating systems.

**Pull request closed without merging**
