### PR TITLE
Arcolinux small ascii logo issue 1146

### PR DESCRIPTION
**Pull request by erikdubois**
see issue #1146

### CODE REVIEW

**Comment by konimex** [comment]
What's `git-v1.sh`?

**Comment by erikdubois** [comment]
delete that
script for github maintenance

Op za 29 dec. 2018 om 14:48 schreef M. Herdiansyah <notifications@github.com

**Comment by dylanaraps** [comment]
added manually.

**Comment by erikdubois** [comment]
thanks

**Pull request closed without merging**
