### PR TITLE
display refresh rate after each monitor (optional)

### PR DESCRIPTION
**Pull request by iandrewt**
Display refresh rate with `--refresh_rate on`

TODO:

- [x] Linux/BSD support
- [ ] Windows support

This closes **#159**

### CODE REVIEW

**Comment by dylanaraps** [comment]
I've finished the Linux support, how do I merge it into this? hm

**Comment by dylanaraps** [comment]
Gitter seems to have btoken the newlines so here's a formatted version.

```sh
"Linux" | *"BSD") 
    if type -p xrandr >/dev/null 2>&1; then 
        resolution=$(xrandr --nograb --current | awk 'match($0,/[0-9]{2,3}.[0-9]{2}\*/) {printf $1 " @ " substr($0,RSTART,RLENGTH) "Hz, "}') 
        resolution=${resolution//\*} 
    elif type -p xdpyinfo >/dev/null 2>&1; then 
        resolution=$(xdpyinfo 2>/dev/null | awk '/dimensions:/ {printf $2}') 
    fi 
;;

```

**Comment by dylanaraps** [comment]
You should also `xrandr` as an optional dependency in the readme.

**Comment by iandrewt** [comment]
Should I add a check for whether the user wants the refresh rate function on or off?

**Comment by iandrewt** [comment]
merge conflict is probably in the README...

**Comment by dylanaraps** [comment]
Remove the readme stuff and I'll add it manually.

**Comment by dylanaraps** [comment]
Swap the if line for xrandr with this one:

```sh
if type -p xrandr >/dev/null 2>&1 && [ "$refresh_rate" == "on" ]; then 
```

**Comment by iandrewt** [comment]
Done!

**Comment by dylanaraps** [comment]
Actually, we should add an option to use xrandr without refresh rates showing. 

```sh
"Linux" | *"BSD") 
    if type -p xrandr >/dev/null 2>&1; then
        case "$refresh_rate" in
            "on") resolution=$(xrandr --nograb --current | awk 'match($0,/[0-9]{2,3}.[0-9]{2}\*/) {printf $1 " @ " substr($0,RSTART,RLENGTH) "Hz, "}') ;;
            "off") resolution=$(xrandr --nograb --current | awk '/*/ {printf $1 ", "}') ;;
        esac
        resolution=${resolution//\*}

    elif type -p xdpyinfo >/dev/null 2>&1; then 
        resolution=$(xdpyinfo 2>/dev/null | awk '/dimensions:/ {printf $2}') 
    fi 
;;
```

**Comment by dylanaraps** [comment]
I'm booting up a Windows VM so I can add Windows support, we should be able to close this PR by tonight. :)

**Comment by iandrewt** [comment]
Awesome!

**Comment by dylanaraps** [comment]
:+1:

**Pull request merged**
