### PR TITLE
Add Hybrid Linux ASCII Logo

### PR DESCRIPTION
**Pull request by norz3n**
## Description

Adding ASCII Distribution Logo for Hybrid Linux

### CODE REVIEW

**Comment by FabioLolix** [comment]
Where can be downloaded the OS?

**Comment by norz3n** [comment]
It's still a work in progress, most of the elements are ready, just a few things left to finish

**Comment by hykilpikonna** [comment]
Looks good

image

**Comment by hykilpikonna** [comment]
Thank you for your contribution! 

This PR is [merged into hyfetch](https://github.com/hykilpikonna/hyfetch/commit/2ebf79a0) since this repo (dylanaraps/neofetch) seems no longer maintained.

[HyFetch](https://github.com/hykilpikonna/hyfetch) is a fork of neofetch with LGBTQ pride flags, but the repo also maintains an updated version of the original neofetch, addressing many pull requests that are not merged in the original repo.

Read the ["Running Updated Original Neofetch" section](https://github.com/hykilpikonna/hyfetch#running-updated-original-neofetch) for more info!

**Pull request closed without merging**
