### PR TITLE
New ASCII logo for Fedora

### PR DESCRIPTION
**Pull request by klpnt**
## Description

New ASCII logo added for Fedora was given the approval in this issue [https://github.com/dylanaraps/neofetch/issues/1711](https://github.com/dylanaraps/neofetch/issues/1711)

### CODE REVIEW

**Comment by Schmensch** [comment]
This. Wanted to make a commit like that, but it already exists

**Comment by TorchedSammy** [comment]
the old logo has a small version, what about this one?

**Comment by klpnt** [comment]
I did create a small version for pfetch and neofetch but wasn't sure if i should include it unless you have something better. I didn't get a response about it.
FedoraASCII_pfetch

**Comment by gnomie14** [comment]
@klpnt I tried making a small version of the logo myself. 
image
[Fedora_Small_ASCII.txt](https://github.com/dylanaraps/neofetch/files/6681742/Fedora_Small_ASCII.txt)
Can you please make a pull request for a small version of the logo using whichever you feel is better?

**Pull request merged**
