### PR TITLE
Change Windows' DE name to "Windows Explorer"

### PR DESCRIPTION
**Pull request by AdrUlb**
## Description
The Windows Desktop Environment is part of Windows Explorer which would make it the DE on Windows

### CODE REVIEW

**Comment by rashil2000** [comment]
#1571

**Comment by AdrUlb** [comment]
WM is actually correctly reporting as DWM.exe now, all that's left to fix is the DE

**Comment by rashil2000** [comment]
The DEs are correct. Try visiting the references in the issue I linked.

**Comment by AdrUlb** [comment]
If you actually read through the article carefully it states that the Windows shell supports various *Visual Styles* and then lists them of, which are the Aero theme on Vista and 7, the Metro theme on Windows 8 and the Fluent theme on Windows 10, it does not state that these are the names of the DEs on the respective operating systems.

**Comment by rashil2000** [comment]
The thing is, the concept of DEs is a Unix thing; it doesn't really fit well with Windows based systems. 

However, for the sake of distinction between the different versions, it makes sense to list out whatever visual styles the Windows Explorer provides.

Replacing them all with a single term would make it too generic.

**Comment by AdrUlb** [comment]
There are custom desktop environments available for Windows, such as the Cairo Desktop Environment, they are not exclusively a UNIX thing. Luna, Aero, Metro and Fluent are themes. They should be displayed as themes or not at all. If this is really needed for distinction purposes I'd suggest both displaying the themes Luna, Aero, Metro and Fluent under the theme section and perhaps appending the Windows version to the Windows Explorer text in parantheses.

I however have decided to close this PR because every time I comment on it a new comment appears stating subjective reasons to keep objectively wrong terminology: "Windows Explorer" (or "Windows shell") is the default (and not the only) Desktop Environment, the concept of different Desktop Environments did emerge with UNIX but it is NOT a UNIX-only idea and Luna, Aero, Metro and Fluent are themes and not DEs and should either be displayed as such or not at all. What you are advocating for is the wrong solution to the distinction problem.

**Pull request closed without merging**
