### PR TITLE
Add Album to the Song function

### LINKED ISSUE #836: Add album variable to Song feature
If possible, I would appreciate it if an album variable was added to neofetch's Song feature instead of just having the "Song" and "Artist" variables. The Album variable could be a separate setting one could toggle, or it could be part of the song shorthand toggle being set to "on". It's always nice if the album name is displayed, at least to me, so I would really appreciate it if this was added.

### PR DESCRIPTION
**Pull request by iandrewt**
## Description

Adds the Album name for songs to the `get_song` function. Resolves #836 

## Features

Supports `--song_shorthand`, putting the Album name on a seperate line
Fixes music players that use `osascript`, replacing the `\` newline escapes with `¬` carriage return because AppleScript just _loves_ to be different

## Issues

Needs testing for other music players. If someone can test with a dbus based player and it works I'll mark all of the dbus players off as working

## TODO

Test on all music players

 - [x] mpd
 - [x] cmus (works in theory)
 - [x] mocp
 - [x] Spotify (Linux) (dbus)
 - [x] Spotify (Mac) (works in theory)
 - [x] Google Play Music Desktop Player (I'll just push an update to `gmpdp-remote` for the dozen or so people who use it 😜)
 - [x] iTunes
 - [x] rhythmbox
 - [x] banshee
 - [x] amarok
 - [x] deadbeef
 - [x] audacious
 - [x] xmms2d
 - [x] gnome-music (dbus)
 - [x] lollypop (dbus)
 - [x] clementine (dbus)
 - [x] pragha
 - [x] exaile
 - [x] juk (dbus)
 - [x] bluemindo (dbus)
 - [x] guayadeque (dbus)
 - [x] yarock (dbus)
 - [x] qmmp
 - [x] quodlibet
 - [x] deepin-music (dbus)
 - [x] tomahawk (dbus)
 - [x] pogo
 - [x] elisa (dbus)

### CODE REVIEW

**Comment by KamranMackey** [comment]
This works with dbus-based players such as Spotify, however cmus fails to work and ends up printing the album name and song title on the "Album" line. I've attached a screenshot of the issue below.

image

But yeah, Spotify and other dbus players work A OK.  Screenshot of it working is below.
image

**Comment by iandrewt** [comment]
The SSD in my hackintosh died yesterday, I’ll be able to continue working on this tomorrow. The cmus one is a bit odd because I keep getting leading and trailing whitespace, if I haven’t figured it out I’ll post what I’m seeing once I have a working computer again

**Comment by KamranMackey** [comment]
Alright, I can wait until then.

**Comment by iandrewt** [comment]
@KamranMackey I've pushed an update to this branch that should fix the output with cmus.

**Comment by KamranMackey** [comment]
Alright, I’ll test it out as soon as I can. At the moment I have a cold and I haven’t been on my computer much the past few days. But hopefully I’ll be able to test it tomorrow.

**Comment by iandrewt** [comment]
All good, there's still plenty to do with this anyway (gotta add support for other players), so no rush

**Comment by KamranMackey** [comment]
@iandrewt Any status with regards to the progress of this?

**Comment by iandrewt** [comment]
Been a bit busy with work and haven't had macOS or Linux on my main computer for a while, I'm reinstalling macOS tomorrow though so I'll be able to continue working on it soon. Did you test it in the media players you use?

**Comment by KamranMackey** [comment]
Yeah I have. Everything works ok in the media players I use.

**Comment by mstraube** [comment]
Hi, I added album support for most of the players in the TODO list. (see #885)
I also can confirm that it's working for audacious.

**Comment by dylanaraps** [comment]
btw, we need to add checks for when either of the tags are empty. I'm not sure about how much of this the current code does.

**Comment by mstraube** [comment]
Maybe something like [this](https://github.com/mstraube/neofetch/blob/8725c502477e43807b92158dcf5205be3430d5aa/neofetch#L1519-L1541)? 8725c502477e43807b92158dcf5205be3430d5aa

The [string splitting](https://github.com/mstraube/neofetch/blob/8725c502477e43807b92158dcf5205be3430d5aa/neofetch#L1523-L1527) won't work properly if one of the tags contain a `-`, but that's already the case with `song_shorthand on` in the current code.

Maybe it would be a good idea to use another delimter? e.g. `--` instead of `-` (see 46eda03d69d8d53df9af4f09f54b3a36c7d5a2fa)
The only thing that's not so nice is that it requires three calls to `audtool`, and I'm not sure about `gpmdp-remote`.

Just some ideas. :)

**Comment by iandrewt** [comment]
@mstraube what's the issue with `gpmdp-remote`? I'm not really able to test any changes I make to it because I don't use GPM anymore, but if theres something that needs to be changed to accomodate for this PR I'll try implement it

**Comment by iandrewt** [comment]
Also changing the delimiter is probably a good idea, as it is now it works as expected when the album has a `-` in it, but not if the song or artist has it. I'd be in favour of using `--`, but we'll see what @dylanaraps thinks

**Comment by dylanaraps** [comment]
This works for me and we won't have to change the delimiter.

```sh
    [[ "$song" != *[a-z]* ]] && unset -v song
```

**Comment by iandrewt** [comment]
Does that replace [line 1521](https://github.com/dylanaraps/neofetch/blob/song-album/neofetch#L1521) or is it seperate?

**Comment by dylanaraps** [comment]
Replace. Sorry, I should’ve been clearer.

**Comment by iandrewt** [comment]
Not working for me, here's an example:

`--song_shorthand off: Approaching Nirvana - Notes - Face-Off`
```
--song_shorthand on:
Artist: Approaching Nirvana
Album: Notes
Song: Off
```

**Comment by dylanaraps** [comment]
Ah I see. I didn’t try shorthand mode. When I get home I’ll look at this in-depth.

**Comment by mstraube** [comment]
>what's the issue with gpmdp-remote?

Hm, I don't remember, but I think I had concerns because I couldn't test it.

**Comment by dylanaraps** [comment]
This works for me with Spotify and `cmus`.

```sh
    [[ "$song" != *[a-z]* ]] && unset -v song

    # Display Artist, Album and Title on separate lines.
    if [[ "$song_shorthand" == "on" && "$song" ]]; then
        artist="${song/ -*}"
        album="${song#*- }"
        album="${album% -*}"
        song="${song/*-}"

        [[ "$(trim "$artist")" ]] && prin "Artist" "$artist"
        [[ "$(trim "$album")" ]]  && prin "Album" "$album"
        [[ "$(trim "$song")" ]]   && prin "Song" "$song"
    fi
```

The separator needs to be changed to something else to completely solve the issue. Can we find an ascii character that won't occur in the song metadata?

**Comment by dylanaraps** [comment]
See: https://github.com/dylanaraps/neofetch/pull/976

This replaces the separator and fixes all issues for me.

**Comment by mstraube** [comment]
With #978 audacious works for me with both, song_shorthand on and off.

**Comment by dylanaraps** [comment]
Is this ready to merge now?

**Comment by iandrewt** [comment]
Yes, I believe so 😀

**Pull request merged**
