### PR TITLE
Add support for SerenityOS

### PR DESCRIPTION
**Pull request by supercomputer7**
## Description

Add support for the SerenityOS operating system.
I read the contribution guidelines. Not very sure if all the usage of `jq` utility is permitted. Let me know if there's something to fix :)
I'll wait for the travis hook to ensure shellcheck runs OK on this PR.

Thank you for your attention :)

### CODE REVIEW

**Comment by supercomputer7** [comment]
I ran shellcheck on the script, it seems that there are 3 warnings not related to anything I changed in this patch.

**Comment by supercomputer7** [comment]
If there's something I can do about this non-related issues with `shellcheck`, please let me know.
Also, how do I run the travis hook for running `shellcheck` on this pull request?

cc @C47F15H

**Comment by dylanaraps** [comment]
I will leave a review when I have time to do so. Thanks for the PR.

**Comment by supercomputer7** [comment]
@dylanaraps Anything new on this?

**Comment by supercomputer7** [comment]
Is there something I can do to make this pull request to be merged?

**Comment by supercomputer7** [comment]
Anything new on this?...

**Comment by supercomputer7** [comment]
I'll try this later.

**Pull request closed without merging**
