### PR TITLE
Song: Rewrite song function

### PR DESCRIPTION
**Pull request by dylanaraps**
Rewrite song function to check process list once instead of multiple times. This speeds up the entire function.

Testing:

- [x] mpd
- [x] cmus
- [x] mocp 
- [x] Spotify
- [x] Google Play Desktop
- [x] iTunes.app
- [x] rhythmbox
- [x] banshee
- [x] amarok
- [x] deadbeef
- [x] audacious

### CODE REVIEW

**Comment by dylanaraps** [comment]
I would appreciate it if you guys could test out the remaining players, I don't have them installed and some of them don't run on Linux.

Thanks

**Comment by iandrewt** [comment]
Not working for iTunes or Google Play Music Desktop Player, the output of the two awk command on my mac and linux computer are:

iTunes (macOS): `/Applications/iTunes.app/Contents/MacOS/iTunes ` (space at end)
GPMDP (macOS): `/Applications/Google Play`
GPMDP (Arch Linux, installed from AUR): `/usr/share/gpmdp/Google Play`

**Comment by dylanaraps** [comment]
It looks like I'm assuming there won't be a path in the field, should be an easy fix.

**Comment by dylanaraps** [comment]
Try now.

**Comment by iandrewt** [comment]
GPMDP is working fine on both computers now, iTunes still isn't working. It looks like the new case statement is making it `iTunes` instead of `iTunes.app`. Removing the `.app` portion makes it work fine.

**Comment by dylanaraps** [comment]
Ah alright

**Comment by dylanaraps** [comment]
Fixed.

**Comment by iandrewt** [comment]
Oops I forgot to specify that the change should be on line `1173` and not `1124`

**Comment by dylanaraps** [comment]
Lol, np

**Comment by dylanaraps** [comment]
Fixed.

**Comment by iandrewt** [comment]
All working perfectly here 👍

**Comment by dylanaraps** [comment]
Thanks!

**Pull request merged**
