### PR TITLE
Add Enso Support

### PR DESCRIPTION
**Pull request by jcckg**
## Description

Only fill in the fields below if relevant.

## Features
Added Enso Logo ASCII Art
Added support for Enso (added case for /etc/os-release)

## Issues
No issues created with modifications. (to my knowledge)

## TODO
Nothing.

### CODE REVIEW

**Review by hykilpikonna — APPROVED** [review]

**Comment by hykilpikonna** [comment]
looks good! 

image
image

**Comment by hykilpikonna** [comment]
Thank you for your contribution! 

This PR is [merged into hyfetch](https://github.com/hykilpikonna/hyfetch/commit/21cffcc4) since this repo (dylanaraps/neofetch) seems no longer maintained.

[HyFetch](https://github.com/hykilpikonna/hyfetch) is a fork of neofetch with LGBTQ pride flags, but the repo also maintains an updated version of the original neofetch, addressing many pull requests that are not merged in the original repo.

Read the ["Running Updated Original Neofetch" section](https://github.com/hykilpikonna/hyfetch#running-updated-original-neofetch) for more info!

**Comment by jcckg** [comment]
Amazing! :)

**Comment by FabioLolix** [comment]
I would guess you are not affiliated with Enso OS https://distrowatch.com/table.php?distribution=enso ?

When there will be a public release?

**Comment by jcckg** [comment]
No affiliation with Enso OS.

We're looking to release a private beta in Q3 2023, and a public beta in Q1/Q2 2024 - however, these may change with the speed of development, and other factors.

**Comment by FabioLolix** [comment]
When have started the development?

**Comment by jcckg** [comment]
Prototyping and designing began at the start of the year, however development has only started in June.

**Pull request closed without merging**
