### PR TITLE
Progress bar support.

### PR DESCRIPTION
**Pull request by dylanaraps**
This PR adds support for displaying a progress bar after certain info functions.

2016-03-03-141308_206x30_scrot

The progress bars are disabled by default and can be enabled by changing these
flags/options to `on`.

- `cpu_usage_bar`
- `memory_bar`
- `battery_bar`
- `disk_bar`

Features:

- Print a progress bar in the `Memory`, `CPU Usage`, `Battery` and `Disk` info functions.
- No loss in speed, the progress bar function is very simple. 
- New function `cpu_usage` to print the cpu usage as a percentage.
- You can customize the length, colors and character used to render the progress bar.

Known bugs:

- [x] ~~Memory progress bar is innacurate and doesn't work when ram is < 1GB used.~~
- [x] ~~Memory may not work on Windows and Mac OS X.~~

Unfinished: 

- [x] ~~Add progress bar support for `Disk Usage`.~~

Please test this out and let me know what you think! :)

### CODE REVIEW

**Comment by tudurom** [comment]
I'm impressed. Can you deactivate the text and only use the progress bar? It would be a great feature for using fetch in lemonbars.

**Comment by dylanaraps** [comment]
The progress bars are unusable in lemonbar because they're completely uncolored. We'll
have to add an option to color them using lemonbar's color format `${X}`.

**Comment by dylanaraps** [comment]
This PR is getting a little too big imo, how can we reduce the size of it?

**Comment by tudurom** [comment]
One PR for progress bars and another one for lemonbar colors.

**Comment by dylanaraps** [comment]
What I'm saying is that the PR for the progress bars on their own is too big. I think
we need to rethink the config options/flags as there's too many in this PR.

**Comment by tudurom** [comment]
It's big because it needs to be.

**Comment by dylanaraps** [comment]
We now have some merge conflicts! doh

**Comment by iandrewt** [comment]
They were there before I started working on it lol. I can't see what they are though

**Comment by dylanaraps** [comment]
It's probably the changelog, I'll just remove it from the PR.

The new changes work really well, nice job!

**Comment by iandrewt** [comment]
What's left to do before this is merged now? Just testing?

And is the `getcpu_usage()` function still needed now that it's embedded into the `cpu_display` option?

**Comment by dylanaraps** [comment]
I'm testing atm.

Bugs:

- [ ] Progress bars don't work on multi battery linux setups.

**Comment by dylanaraps** [comment]
I don't know why we're getting conflicts though. Should I manually add all of these changes to master and open another PR?

**Comment by dylanaraps** [comment]
TODO (After merge)

- [ ] Changelog
- [ ] Man page

**Comment by iandrewt** [comment]
Yeah probably add to master, it'll happen at some point anyway and it's not broken or anything

**Comment by dylanaraps** [comment]
I'm fixing the merge commits on the cmdline so this PR can be merged normally.

**Comment by dylanaraps** [comment]
That was easier then I though. :+1:

**Comment by iandrewt** [comment]
Where was the conflict? Was it in the `cpu_shorthand` part?

**Comment by dylanaraps** [comment]
Yup, there was also a tiny conflict with the `cpu_display` config option.

**Comment by dylanaraps** [comment]
I'm going to do the Changelog/Man page now.

**Comment by iandrewt** [comment]
Awesome!

**Comment by dylanaraps** [comment]
Thanks for the help again.

**Pull request merged**
