### PR TITLE
Add distribution AmogOS

### PR DESCRIPTION
**Pull request by Gyro7**
## Description

I added the distro AmogOS

### CODE REVIEW

**Comment by dylanaraps** [comment]
Please fix indentation and remove unrelated changes from this PR.

**Comment by Gyro7** [comment]
I did it @dylanaraps , there is an error tho, idk why, that's the "unrelated change" u told me.
I put it back but it can't execute if I don't remove the parenthesis at line 2619, it's a syntax error.

**Comment by dylanaraps** [comment]
My bad. I see now. :)

**Comment by Gyro7** [comment]
Thanks <3

**Pull request merged**
