### PR TITLE
Config: Move default config to /etc (#620)

### PR DESCRIPTION
**Pull request by konimex**
## Description

Self-titled.

If this looks good enough, please merge it (and update the changelogs accordingly) as I won't be able to open my desktop for the next 6-8 hours.

### CODE REVIEW

**Comment by dylanaraps** [comment]
We can remove the check for `/usr/local/share` now since we're only installing the config to `/etc/`. Other than that LGTM. I can make this change after merging this if you'd like. :+1:

**Comment by konimex** [comment]
Please do. :+1:

**Comment by dylanaraps** [comment]
One thing: 

```sh
PREFIX=/usr/local make install
```

This doesn't work, neofetch is still put in `/usr/bin`. I'm pretty sure this is happening because the `PREFIX = /usr` part of the Makefile overwrites the user's env. This is also probably the reason why we were using `=?`. I'll look into this.

**Comment by konimex** [comment]
How about `make PREFIX=/usr/local install`?

On 18 January 2017 8:56:24 AM GMT+07:00, Dylan Araps <notifications@github.com> wrote:
>One thing: 
>
>```sh
>PREFIX=/usr/local make install
>```
>
>This doesn't work, neofetch is still put in `/usr/bin`. I'm pretty sure
>this is happening because the `PREFIX = /usr` part of the Makefile
>overwrites the user's env. This is also probably the reason why we were
>using `=?`. I'll look into this.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dylanaraps/neofetch/pull/622#issuecomment-273359994

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by konimex** [comment]
Ah, yes. Please do.

On 18 January 2017 8:34:08 AM GMT+07:00, Dylan Araps <notifications@github.com> wrote:
>We can remove the check for `/usr/local/share` now since we're only
>installing the config to `/etc/`. Other than that LGTM. I can make this
>change after merging this if you'd like. :+1:
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dylanaraps/neofetch/pull/622#issuecomment-273356364

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dylanaraps** [comment]
That worked. :+1:

**Pull request merged**
