### PR TITLE
Fix GPU listing for Windows

### PR DESCRIPTION
**Pull request by lucaspbastos**
## Description

Fix for GPU listing on Windows having extraneous values like blank lines or "Description" from Win32_videocontroller.

### CODE REVIEW

**Comment by dylanaraps** [comment]
Send me the full output of: `wmic path Win32_VideoController get caption`. The fix is simpler than what is done in this PR. :+1:

**Comment by lucaspbastos** [comment]
> 
> 
> Send me the full output of: `wmic path Win32_VideoController get caption`. The fix is simpler than what is done in this PR. 👍

This is my output and what was also previously getting read as three separate GPU's:
`Caption
AMD Radeon (TM) R9 390 Series

`

**Comment by rashil2000** [comment]
For me it looks like this: 
```
Caption
NVIDIA GeForce GTX 1060

```

**Comment by dylanaraps** [comment]
Please try latest master.

**Comment by lucaspbastos** [comment]
> 
> 
> Please try latest master.

Still getting an extra blank line, but not seeing "GPU: Caption" anymore.
neofetch

**Comment by dylanaraps** [comment]
Try latest master, should be fixed.

**Comment by lucaspbastos** [comment]
Same output unfortunately.

**Comment by rashil2000** [comment]
Yes, same, tried on latest master.

**Comment by dylanaraps** [comment]
Try the latest master (WM output fixed as well).

**Comment by lucaspbastos** [comment]
Still the same output.

**Comment by dylanaraps** [comment]
I can't reproduce using the output you have attached above as input. I don't have Windows so I cannot test this on a Windows machine. Any help is appreciated.

**Comment by rashil2000** [comment]
The GPU and WM are working correctly now.

**Comment by lucaspbastos** [comment]
Output working for me as well with the recent changes!

**Pull request closed without merging**
