### PR TITLE
Support screen resolution on Windows 10

### PR DESCRIPTION
**Pull request by dar-irl**
Edited the WMIC command used so that the screen resolution can be obtained on Windows 10.

### CODE REVIEW

**Comment by dylanaraps** [comment]
Thanks for the PR, does this also work on other version of Windows? (XP, 7)

**Comment by dar-irl** [comment]
I've tested it on Win7 and it works fine. I'll see if I can get WinXP on a VM to check it out.

**Comment by dylanaraps** [comment]
Sweet, thanks.

**Comment by dylanaraps** [comment]
Let me know if you can't get a VM and I can test it at uni today.

**Comment by dar-irl** [comment]
I'm having issues getting mine to run WinXP, sorry!

**Comment by dylanaraps** [comment]
All good, I'll be in class In about an hour so I'll test then.

**Comment by dylanaraps** [comment]
It works on XP, I'll merge this now.

Thanks.

**Pull request merged**
