### PR TITLE
Tweaked function for obtaining host model

### PR DESCRIPTION
**Pull request by RealStr1ke**
## Description

I've been using the official Arch Linux package for neofetch and I have a Lenovo laptop. When switching over to the git repo version, I noticed that the field for host changed to a less descriptive version of my host:
```
 Host  81XA Lenovo IdeaPad S540-13IML
↓↓↓
 Host  LENOVO LNVNB161216
```
I looked over the function and saw what caused that to happen (check commit). I'm not sure if this was intentional and it probably is hardware-specific but I thought I'd make a PR incase other people noticed this and incase it's possible for other devices to have a more descriptive host field than seen before.

## Features
- `More descriptive host info field`

### CODE REVIEW

**Comment by RealStr1ke** [comment]
My commit: [`25d8e2f` (#2238)](https://github.com/dylanaraps/neofetch/pull/2238/commits/25d8e2f10e402c948e7b305347832b7e817e9144)
(Accidentally PR-ed a fork of hyfetch all the way back to neofetch 💀 )

**Comment by hykilpikonna** [comment]
so many commits lol

yea I can probably merge this without adding any duplicate commits, let me try

**Comment by hykilpikonna** [comment]
It worked! :D

But in the future, please either submit the PR in the hyfetch repo, or if you want to submit the PR here, please make the changes based on dylanaraps/neofetch:master instead. There's no way anyone would merge this into neofetch lol

**Comment by RealStr1ke** [comment]
Yeah minor mistake since I accidentally forked hyfetch instead of neofetch, but thanks! 😅

**Pull request closed without merging**
