### PR TITLE
Add LangitKetujuh OS

### PR DESCRIPTION
**Pull request by hervyqa**
## Description

LangitKetujuh GNU/Linux based on voidlinux.
homepage: https://langitketujuh.id

Terminal:
Screenshot_20210714_125415

Splash screen logo:
Screenshot_langitketujuh_2021-07-14_13:12:53

### CODE REVIEW

**Comment by C47F15H** [comment]
Because @dylanaraps has not allowed unicode eblock elements except **really** needed, you can try this:
```
 '*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
c.   `*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMm+,   `"+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMm,  `"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMl                                     |MMMMMMMMM
MMMMMMMMMl                _____________________|MMMMMMMMM
MMMMMMMMMl                `"°°MMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMl                      "*MMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMl                          "*lMMMMMMMMMMMMMMMMMM
MMMMMMMMMl                             `¯¯¯¯¯¯¯MMMMMMMMMM
MMMMMMMMMl_______________________________      MMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmc.   `"MMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+.   `*MMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+.  `"
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+.

```

**Comment by hervyqa** [comment]
i see. ok, i will fix it first. thanks @C47F15H

**Comment by hervyqa** [comment]
ascii logo with letter "L7" as LangitKetujuh linux identity.

Screenshot_20210714_194928

**Comment by hervyqa** [comment]
hi @dylanaraps, any suggestions for improvement?

**Pull request merged**
