### PR TITLE
OS: Added initial support for MINIX

### PR DESCRIPTION
**Pull request by konimex**
## Description

This adds initial support for MINIX.

## Issues

This only supports [Minix R3.4rc](http://download.minix3.org/iso/snapshot/minix_R3.4.0rc2-373b793.iso.bz2) and up, because `sysctl` was ported (from NetBSD!) just this January (before R3.4.0rc was released), however I'm yet to test this in MINIX 3.3 so maybe I can find a workaround (maybe using `top -d 1`).

Some functions also didn't appear because when a system is installed, it was a real barebone system. No `dig`, no `curl`, no `wget`.

virtualbox_minix3 clone_18_12_2016_21_52_11

## TODO

TBA

### CODE REVIEW

**Comment by dylanaraps** [comment]
Neat!

LGTM so far.

**Comment by dylanaraps** [comment]
Here's some ascii art for Minix, this is the best I could do since we're limited with colors:

```sh
${c2}   -sdhyo+:-`                -/syymm:
   sdyooymmNNy.     ``    .smNmmdysNd
   odyoso+syNNmysoyhhdhsoomNmm+/osdm/
    :hhy+-/syNNmddhddddddmNMNo:sdNd:
     `smNNdNmmNmddddddddddmmmmmmmy`
   `ohhhhdddddmmNNdmddNmNNmdddddmdh-
   odNNNmdyo/:/-/hNddNy-`..-+ydNNNmd:
 `+mNho:`   smmd/ sNNh :dmms`   -+ymmo.
-od/       -m${c1}mm${c2}mo -NN+ +m${c1}mm${c2}m-       yms:
+sms -.`    :so:  .NN+  :os/     .-`mNh:
.-hyh+:////-     -sNNd:`    .--://ohNs-
 `:hNNNNNNNMMd/sNMmhsdMMh/ymmNNNmmNNy/
  -+sNNNNMMNNNsmNMo: :NNmymNNNNMMMms:
    //oydNMMMMydMMNysNMMmsMMMMMNyo/`
       ../-yNMMy--/::/-.sMMmos+.`
           -+oyhNsooo+omy/```
              `::ohdmds-`
```

Here's the distro colors section: 

```sh
        "debian"* | "ubuntu"* | "dragonfly"* | "pacbsd"* | "oracle"* | "blankon"* | "dracos"* | "peppermint"* | "minix"*)
            set_colors 1 7 3
        ;;
```

Here's a screenshot:

2016-12-19-111801_711x691_scrot

**Comment by dylanaraps** [comment]
Oops, I went to open a pull request for the ascii art and it auto merged it into your PR. Anyway, here's how it looks on Minix:

2016-12-19-114045_730x423_scrot

**Comment by dylanaraps** [comment]
Bugs:

- When shell is set to `sh` the command fails since `--version` doesn't exist.
    - Fix: Add `2>/dev/null` to the `--version` command.
    - Fix2: Add a new match for `sh` in the case that does nothing.
- Terminal is set to `(init)`.
    - Fix: Add `(init)` to the `get_term()` case. Example:

```sh
# Old
"login"* | *"Login"* | "init") term="$(tty)" ;;

# New
"login"* | *"Login"* | "init" | "(init)") term="$(tty)" ;;
```

- Some escape sequences aren't supported and there's garbage in the tty.
    - `25h7h10(?)
    - `25l7l`(?)

**Comment by konimex** [comment]
I'm going ahead and merge this to master, since all essential functions seems to work correctly. The only issue exists now is the escape sequences which isn't supported by MINIX.

**Comment by dylanaraps** [comment]
About the escape sequences: The TTY doesn't support them full stop. Even when using `tput` commands they don't work. We're going to have to find a way to hide the output of them if they fail.

**Pull request merged**
