### PR TITLE
OS: Add support for Parsix

### PR DESCRIPTION
**Pull request by mstraube**
http://www.parsix.org/wiki/WikiStart

parsix

### CODE REVIEW

**Comment by konimex** [comment]
I don't think we should add support of a [shutting down](http://www.parsix.org/wiki/News#ParsixGNULinuxProjectTerminationAnnouncement-May192017) distro.

Although I'm not so sure, since we did add support for a dead OS (IRIX).

**Comment by mstraube** [comment]
Oh, I didn't notice that it's shutting down.

**Comment by dylanaraps** [comment]
If all it requires is ascii art and colors then it's fine by me, anything more than that for a inactive distro is too much.

**Comment by konimex** [comment]
Alright. Merging this one.

**Pull request merged**
