### PR TITLE
Refracta ASCII

### PR DESCRIPTION
**Pull request by DVSUHZ-g**
I love my ''Refracted Devuan GNU/Linux"

### CODE REVIEW

**Comment by dylanaraps** [comment]
Can I see a screenshot?

**Comment by DVSUHZ-g** [comment]
rneohot

**Comment by dylanaraps** [comment]
Is your OS being detected as `Refracted Devuan GNU/Linux` or are you adding that manually? What does a non-modified version of Neofetch display?

**Comment by dylanaraps** [comment]
Cool, I've merged this manually. Thanks =)

**Pull request closed without merging**
