### PR TITLE
WM: Add support for Kwm on macOS

### PR DESCRIPTION
**Pull request by jorgegonzalez**
## Description

This PR adds support for [Kwm](https://github.com/koekeishiya/kwm).

### CODE REVIEW

**Comment by dylanaraps** [comment]
Change the `ps` line to this: 

```sh
ps -e | grep -F -q "kwm" && wm="Kwm"
```

Otherwise LGTM :+1:

**Comment by jorgegonzalez** [comment]
Done.

**Comment by dylanaraps** [comment]
Thanks!

**Comment by jorgegonzalez** [comment]
They always seem to fail on my PRs. Would you happen to know why?

**Comment by dylanaraps** [comment]
Travis runs shellcheck and travis errors if shellcheck doesn't like anything.

**Comment by jorgegonzalez** [comment]
So I made the change you suggested without actually testing it.

`[[ "$(ps -e | grep '[k]wm')" ]] && wm="Kwm"` -> `ps -e | grep -F -q "kwm" && wm="Kwm"`

This change doesn't work as intended.

**Comment by dylanaraps** [comment]
I thought you would've tested it before changing the PR.

What doesn't work exactly?

**Comment by jorgegonzalez** [comment]
My apologies.

The line `ps -e | grep -F -q "kwm" && wm="Kwm"` sets the window manager to "Kwm" even if it isn't actually running as a process.

This happens because the grep process always contains the `"kwm"` string when searching for it. `grep  "[k]wm"` prevents that process from showing up in the output.

https://unix.stackexchange.com/questions/74185/how-can-i-prevent-grep-from-showing-up-in-ps-results?noredirect=1&lq=1

`ps -e | grep -q '[k]wm' && wm="Kwm"`  is the proper fix.

**Comment by dylanaraps** [comment]
That was my fault, don't worry.

Thanks for finding the correct fix. :)

Feel free to open another PR and I'll merge it. :+1:

**Comment by jorgegonzalez** [comment]
Done.

**Pull request merged**
