### PR TITLE
PuffOS neofetch add to database

### PR DESCRIPTION
**Pull request by omeready**
puffos.github.io is website

### CODE REVIEW

**Comment by Caticer** [comment]
lmao

**Comment by forkposix** [comment]
kek

**Comment by frknkrc44** [comment]
Please don't accept this because it corrupts all of logos

**Comment by NaytSeyd** [comment]
looks like a retarded project

**Comment by kutlay1653** [comment]
Turk_guy_kills_neofetch_in_one_cummit_1080p.mp4

**Comment by Caticer** [comment]
@frknkrc44 looks like you didn't know kali's new logo
image

**Comment by kutlay1653** [comment]
@Caticer looks awesome lol

**Comment by SuperCosmicBeing** [comment]
@Caticer Wtf, I'm dying lmfao 😂

**Comment by Zaryob** [comment]
> @frknkrc44 looks like you didn't know kali's new logo
> image

Awesome. This patch must come as nearest as possible

**Pull request closed without merging**
