### PR TITLE
Add Apple Music

### PR DESCRIPTION
**Pull request by ijiki16**
## Description

Add support Apple Music and remove iTunes
 
Screen Shot 2020-11-22 at 17 17 17

## Features
Add support Music app on MacOS
## Issues
[issuse 1484](https://github.com/dylanaraps/neofetch/issues/1484)

### CODE REVIEW

**Comment by dylanaraps** [comment]
Hi. Will only merge this if support for iTunes is retained. Older macOS versions would lose song support with this PR as-is no?

**Comment by ijiki16** [comment]
Ok

**Comment by dylanaraps** [comment]
Fix the indentation. :+1:

**Comment by ijiki16** [comment]
I think,  I have fixed it but don't know for sure. VS Code shows everything the same

**Comment by dylanaraps** [comment]
It's still wrong. See the diff.

**Pull request merged**
