### PR TITLE
Add kitty to the list of available backends

### PR DESCRIPTION
**Pull request by Luflosi**
## Description

`kitty` wasn't in the list of backends, so I added it. Similar to #1091.

## Issues
Should I run `help2man` to generate a new `neofetch.1` man page?

## TODO
The options are in a different order in the many places they appear in. I think we should decide on one order and then stick to it everywhere.

### CODE REVIEW

**Comment by dylanaraps** [comment]
Thanks for the PR! :+1:

> Should I run help2man to generate a new neofetch.1 man page?

If you don't mind, I'd appreciate it. :)

**Comment by Luflosi** [comment]
Running it will add a few more missing things to the manpage. Is that ok or should I make a separate PR?

**Comment by dylanaraps** [comment]
That's fine. :)

**Comment by dylanaraps** [comment]
Thanks :)

**Comment by Luflosi** [comment]
At first I ran `help2man` directly but then I discovered, that neofetch has a command-line option for that.

**Comment by dylanaraps** [comment]
Yeah, it's a simple option to make things a little easier.

**Comment by Luflosi** [comment]
It was very convenient. Without it I wouldn't have known the correct command-line options to use for help2man.

**Pull request merged**
