### PR TITLE
Add Aster Linux Logo

### PR DESCRIPTION
**Pull request by 7thblade**
## Description

Please add my Aster Linux Logo to Neofetch repository

### CODE REVIEW

**Review by hykilpikonna — APPROVED** [review]

**Comment by hykilpikonna** [comment]
Looks good!

image

**Comment by hykilpikonna** [comment]
Thank you for your contribution! 

This PR is [merged into hyfetch](https://github.com/hykilpikonna/hyfetch/commit/18fe75ef) since this repo (dylanaraps/neofetch) seems no longer maintained.

[HyFetch](https://github.com/hykilpikonna/hyfetch) is a fork of neofetch with LGBTQ pride flags, but the repo also maintains an updated version of the original neofetch, addressing many pull requests that are not merged in the original repo.

Read the ["Running Updated Original Neofetch" section](https://github.com/hykilpikonna/hyfetch#running-updated-original-neofetch) for more info!

**Comment by hykilpikonna** [comment]
Actually, please put `"Aster"*` after `"AsteroidOS"*` because the wildcard matching in `Aster*` will always match anything that matches `"AsteroidOS"*`, but not the other way around.

image

**Comment by 7thblade** [comment]
> Looks good!
> 
> image

Thanks! I updated my pull request to  @dylanaraps and installed hyfetch instead of neofetch, didn't knew about your repo before. It's amazing to keep projects like this updating with time

**Pull request closed without merging**
