### PR TITLE
Update Kubuntu Logo

### PR DESCRIPTION
**Pull request by m1st0**
## Description

Updated Kubuntu logo.

### CODE REVIEW

**Comment by konimex** [comment]
LGTM. Thanks for the PR.

**Comment by dylanaraps** [comment]
I wasn't going to merge this since it's inconsistent with the other *buntu ascii art.

**Comment by konimex** [comment]
Well.. Oops.

**Comment by dylanaraps** [comment]
Easy to revert 😁

**Comment by m1st0** [comment]
@dylanaraps You mentioned inconsistency with *buntu ascii art.  I don't understand as the Ubuntu logo on neofetch for Kubuntu 17.10 has blank areas with white as well.  I therefore tried to match the following logo https://commons.wikimedia.org/wiki/File:Antu_distributor-logo-kubuntu.svg for Kubuntu.  Would you like me to change it? Additionally, if creative commons requirements on that link for derivative works requires more work, I suppose we can leave it out or I can add it as a comment in the ASCII art.

**Pull request merged**
