### PR TITLE
Add ITC distro logo

### PR DESCRIPTION
**Pull request by Hyd3r1**
## Description

Only fill in the fields below if relevant.

### CODE REVIEW

**Comment by dylanaraps** [comment]
This logo is too large to be included in Neofetch. Please reduce it to match the sizes of other ASCII logos. :+1:

**Comment by Hyd3r1** [comment]
Okay, i try :)

**Comment by Hyd3r1** [comment]
It's okey?

**Comment by dylanaraps** [comment]
I can't seem to find this distribution around the net. Got a link to its homepage?

**Comment by Hyd3r1** [comment]
https://www.itcenterpl.com/itc (my own distro, it work)

**Comment by dylanaraps** [comment]
Nice, thanks!

**Comment by Hyd3r1** [comment]
Thanks for PR :D

**Pull request merged**
