### PR TITLE
Update gobolinux

### PR DESCRIPTION
**Pull request by WilsonRU**
## Description
Update GoboLinux art

### CODE REVIEW

**Comment by dylanaraps** [comment]
The art needs a `${c1}` tag so that users can customize the color of it. Also all art in neofetch starts at line 1.

**Comment by WilsonRU** [comment]
Okay, I'll be back and I've made the necessary changes.

**Comment by dylanaraps** [comment]
Just a single `${c1}` on the first line will cover the entire file.

**Comment by dylanaraps** [comment]
Example:

```sh
${c1}  _____       _           
 / ____|     | |          
| |  __  ___ | |__   ___  
| | |_ |/ _ \| '_ \ / _ \ 
| |__| | (_) | |_) | (_) |
 \_____|\___/|_.__/ \___/                 
```

**Pull request closed without merging**
