### PR TITLE
Added ApertureScience Logo

### PR DESCRIPTION
**Pull request by LuigiTheHunter**
## Description

Only fill in the fields below if relevant.

## Features
- Added ApertureScience Logo

### CODE REVIEW

**Comment by LuigiTheHunter** [comment]
Hopefully you got the new commit aswell, because I forgot the ;; :)

**Comment by konimex** [comment]
I see no reason to merge this unless "ApertureScience" is an actual Linux distro.

**Comment by LuigiTheHunter** [comment]
> I see no reason to merge this unless "ApertureScience" is an actual Linux distro.

Hmh sad. It looks really good though. But Windows isn't a Linux distro aswell.

**Comment by konimex** [comment]
I should've clarified: A distro or an actual OS. Like Solaris, AIX, etc.

**Comment by konimex** [comment]
>I understand your decision just one question though, what is the downside of adding it?

It would set a dangerous precedent. If we merge this, in the future people will ask to add a Black Mesa logo or a sport team (e.g. Barcelona or Liverpool) logo because they saw this PR being merged, so we have to be fair, and if we have all non-OS related logo included, the filesize will be too big. Either we include them all, or we don't.

Since Dylan seems to endorse my decision here, I'm closing this PR.

**Comment by LuigiTheHunter** [comment]
Thanks for the explanation I fully understand :)

**Pull request closed without merging**
