### PR TITLE
Modifiable info separator

### PR DESCRIPTION
**Pull request by xynxynxyn**
Add ability to modify the default ":" separator.

### CODE REVIEW

**Comment by plgruener** [comment]
May I ask what is your usecase for changing the default ":" separator?
I cannot think of any other commonly used character for that except "=", which has no advantage over the colon in this context, so this PR (which is fine per se) just seems to add another (useless) --option to the already **74** other ones.

(PS: it's spelt sep**a**rator)

**Comment by konimex** [comment]
Much better.

However since this is a new feature, I'll leave it to @dylanaraps to decide if the new feature is acceptable or not.

**Comment by dylanaraps** [comment]
Add some documentation and we're good to go (usage function). I've got a use case for this.

**Comment by dylanaraps** [comment]
Cheers :+1:

**Pull request merged**
