### PR TITLE
Support for Anarchy Linux, Calculate Linux and NuTyX

### PR DESCRIPTION
**Pull request by robertwolter**
I added support for Anarchy Linux, Calculate Linux and NuTyX to neofetch, including ascii-art files.

### CODE REVIEW

**Comment by robertwolter** [comment]
If I remove all white spaces, the ouput gets garbage. You mean the trailing white spaces, not the leading ones ;) I'll check for the correct colors.

**Comment by dylanaraps** [comment]
I mean the leading and trailing white space. The white space surrounding
tenge ASCII art.

Take a look at the other art in Neofetch to get an idea.

**Comment by robertwolter** [comment]
Ok, done. I applied the changes and uploaded the new files to my fork, including the latest changes you made to neofetch.

**Comment by dylanaraps** [comment]
LGTM :+1:

Thanks

**Comment by robertwolter** [comment]
Thanks for merging :)

**Pull request merged**
