### PR TITLE
Image: Rewrite backend handling.

### PR DESCRIPTION
**Pull request by dylanaraps**
## Description

This PR rewrites the handling of all the image backends and will allow us to easily add more backends in the future. (#614)

## Features

- `--image` has been replaced with `--image_backend`.
    - `--image_backend` takes `w3m`, `iterm2`, `tycat`, `ascii` or `off`.
    - Shortcut flags have also been added for the different backends.
        - `--w3m`.
        - `--iterm2`.
        - `--tycat`.
        - `--ascii`.
        - `--off`.
        - `--catimg`.
        - `--caca`.
        - `--jp2a`.
- All image and ascii art file selection has been replaced with `--image_source`.
    - Examples:
        - `neofetch --image_backend w3m--image_source /path/to/img.jpg`
        - `neofetch --image_backend ascii --image_source /path/to/ascii`
    - Added `image_source="auto"` and made it the default value.
        - This will make Neofetch use `wallpaper` in `w3m-img` and etc modes.
        - This will make Neofetch use `distro` in ascii mode.
- More logging was added.
    - Which image file was used.
- The image functions flow clearly now.
- Added image backends `catimg` and `caca`. See #614 
- Added image backend `jp2a`.
- Fixed bugs with image shuffle.
- Removed obsolete config options. 

## Issues

- [x] No error handling if backend program is missing.
- [x] `--size` doesn't update padding.

## TODO

- [x] Possibly rename `--image_backend` and `--image_source` to `something_*`.
- [x] Add shortcut flags for modes.
    - [x] `--w3m`.
    - [x] `--iterm2`.
    - [x] `--tycat`.
    - [x] `--ascii`.
    - [x] `--off`.
- [x] Config file
    - [x] Add new options.
    - [x] Remove old options.
- [x] Documentation.
    - [x] Write documentation.
    - [x] Remove old documentation.
- [x] Add backwards compatibility.
    - [x] Flags.
    - [x] Options.
- [x] Testing
    - This is OS independent so testing will be all about usability, error handling and will be mode specific.
    - [x] `imagemagick` not found.
    - [x] `-z $DISPLAY`
    - [x] Image file not found --> ascii mode.
    - [x] Ascii file not found --> ascii distro mode.
    - [x] Image program not found --> ascii mode.
    - [x] Terminal window size failed --> ascii mode.
    - [x] Unknown image backend specified --> off mode

### CODE REVIEW

**Comment by konimex** [comment]
> `--image_backend` takes `w3m-img`, `iterm2`, `tycat`, `ascii` or `off`.

Does this have a default value when we add this to the config file? (e.g. `image_backend="w3m"`)

If so, we probably add `auto` for automatic handling.

**Comment by dylanaraps** [comment]
Default value is `ascii` (Same as it is in master now).

**Comment by dylanaraps** [comment]
This should be ready once I've come up with a better way to name `--image_backend` and `--image_source`. Backwards compatibility is not 100% possible since `$image_source` exists in `2.0.2`. We can't overwrite the user's setting without conflicting with new config files.

The script won't break with old config files, the only issue is that users with old configs won't get the new default value for `$image_source` (`auto`).

**Comment by dylanaraps** [comment]
I had to make some changes to how the backend stuff worked to add support for `imgcat` and `caca` so it was easier to just merge #614 into this PR.

**Comment by dylanaraps** [comment]
Should we make all of the shortcut flags (`--ascii`, `--w3m` and etc) take a file as an argument? For example:

```sh
# Current behavior
neofetch --w3m --image_source ~/Pictures/Wallpapers/0.jpg
neofetch --ascii --image_source ~/ascii/test

# Proposed behavior
neofetch --w3m ~/Pictures/Wallpapers/0.jpg
neofetch --ascii ~/ascii/test
```

This makes the flags easier to remember and the longer `--image_source` and `--image_backend` are there for those who want it.

**Comment by konimex** [comment]
Few comments about using YAML.

For GPU, the current behavior is:

```yaml
GPU: "Intel Integrated Graphics"
GPU: "AMD Radeon HD 8670A/8670M/8690M"
```

This can be 

```yaml
GPU:
  - "Intel Integrated Graphics"
  - "AMD Radeon HD 8670A/8670M/8690M"
```

For disk, the current behaviour is

```yaml
Disk (/): "8.8G / 267G (4%)"
Disk (/home): "8.3G / 631G (2%)"
```

This can be changed to:

```yaml
Disk:
    /: "8.8G / 267G (4%)"
    /home: "8.3G / 631G (2%)"
```

Take this with a grain of salt as I don't know if YAML accepts slashes as key and how programs read YAML.

**Comment by dylanaraps** [comment]
This is ready to be merged.

Other backends will come later. :D

(Just waiting on travis)

**Pull request merged**
