### PR TITLE
Add ArcheStrike ASCII

### LINKED ISSUE #1311: Please apply ASCII arts for ArchStrike and BlackArch
ArchStrike: https://archstrike.org/
BlackArch: https://blackarch.org/

### PR DESCRIPTION
**Pull request by wwchak**
## Description
Fixes #1311 by adding ArchStrike ASCII based on the official logo from https://github.com/ArchStrike/ArchStrike

Here's a preview of the changes:
ArchStrikeDemo

### CODE REVIEW

**Comment by dylanaraps** [comment]
Thanks for the PR, I am unable to merge this though as it is far too big. Any chance of a smaller ascii art?

**Comment by wwchak** [comment]
I thought it was larger than the others as well. How many lines would be optimal/preferred? 

What do you think of this? There's some compromise on the overall looks though.
Screen Shot 2019-10-16 at 3 11 40 am

**Comment by wwchak** [comment]
How about either one of this? Difference being the top end of the lightning bolt symbol. 

Resize

**Comment by dylanaraps** [comment]
Push it to the repository so that I am able to discern its size. :+1:

**Comment by dylanaraps** [comment]
LGTM :+1:

Thanks!

**Pull request merged**
