### PR TITLE
Added AZOS GNU/Linux

### PR DESCRIPTION
**Pull request by ghost**
just added the ascii logo and an azos in the "alphabetical order distro list"
there is no small variant.

Edit: Updated for recent AZOS GNU/Linux logo change, also the pull req is not draft anymore... yay...

### CODE REVIEW

**Comment by hykilpikonna** [comment]
Maybe the new AZOS logo is a little bit too wide...

Currently, the mean width of an ascii art is 35.59 characters, with a standard deviation of 10.16 characters (excluding color codes). The new AZOS logo is 71 characters wide... it will in fact be the widest logo in neofetch if it's accepted.

You might want to shorten it a bit, though I guess it's also okay if you decide not to. Please let me know.

image

image

**Comment by ghost** [comment]
> Maybe the new AZOS logo is a little bit too wide...
> 
> Currently, the mean width of an ascii art is 35.59 characters, with a standard deviation of 10.16 characters (excluding color codes). The new AZOS logo is 71 characters wide... it will in fact be the widest logo in neofetch if it's accepted.
> 
> You might want to shorten it a bit, though I guess it's also okay if you decide not to. Please let me know.
> image image

guess you gotta make a world record from time to time lmao

Just kidding obviously. Will look into it. Stand-by.

**Comment by ghost** [comment]
@hykilpikonna there you go, sorry for the reply time, uhh... yeah... guess the logo lost some weight :D

**Comment by hykilpikonna** [comment]
Looks good!

image

Thank you for your contribution! 

This PR is [merged into hyfetch](https://github.com/hykilpikonna/hyfetch/commit/b87bb475) since this repo (dylanaraps/neofetch) seems no longer maintained.

[HyFetch](https://github.com/hykilpikonna/hyfetch) is a fork of neofetch with LGBTQ pride flags, but the repo also maintains an updated version of the original neofetch, addressing many pull requests that are not merged in the original repo.

Read the ["Running Updated Original Neofetch" section](https://github.com/hykilpikonna/hyfetch#running-updated-original-neofetch) for more info!

**Comment by ghost** [comment]
You are welcome! (and thank you!)

**Pull request closed without merging**
