### PR TITLE
Updated Raspbian logo with a clearer version

### PR DESCRIPTION
**Pull request by stefanb**
Updated Raspbian logo with a clearer version
image
Top left old Raspbian logo, 
Bottom left Ubuntu logo
Top right new Raspbian on white background
Bottom right new Raspbian on black background

### CODE REVIEW

**Comment by dylanaraps** [comment]
The only problem I have with the new logo is the height, it's too tall. I'll merge this if it can be made closer to the sizes of the other logos.

**Comment by dylanaraps** [comment]
Updated with this art:

rasp

**Comment by stefanb** [comment]
Perfect! 
I'm curious; What tool did you use to generate the ASCI art?

**Comment by dylanaraps** [comment]
This website: http://www.text-image.com/convert/ascii.html

Settings:

- Invert colors
- Increase contrast
- Rest is default

Image used:

rasp

**Pull request closed without merging**
