### PR TITLE
fixed cmus properly, now works regardless of output order

### PR DESCRIPTION
**Pull request by iandrewt**
Got it working in one call of `cmus-remote -Q` too :+1:

### CODE REVIEW

**Comment by dylanaraps** [comment]
I think this approach is better:

```sh
        song=$(cmus-remote -Q | grep "tag artist \|tag title" 2>/dev/null | sort)
        artist="${song##tag artist }"
        artist="${artist%%tag title*}"
        title="${song##*tag title }"
        song="${artist//$'\n'} - $title"
        state=$(cmus-remote -Q | awk -F ' ' '/status/ {printf $2}' 2>/dev/null)
```

- We call `sort` to sort `tag title` and `tag artist` alphabetically.
- We remove the newline using `${artist//$'\n'}` instead of `tr`.

Note: I haven't tested this on OS X.

**Comment by dylanaraps** [comment]
Ok, this is an even better way.

```sh
IFS=$'\n'
song=($(cmus-remote -Q | grep "tag artist \|tag title \|status" 2>/dev/null | sort))
artist=${song[1]/tag artist }
title=${song[2]/tag title }
state=${song[0]/status }

song="$artist - $title"
```

- Uses `sort` and an array.
- Reduce the `cmus-remote` call to once for the entire block.

**Comment by iandrewt** [comment]
Fixed. That's a lot cleaner too!

**Comment by dylanaraps** [comment]
:+1:

**Pull request merged**
