### PR TITLE
Adding PacBSD support to neofetch

### PR DESCRIPTION
**Pull request by vendion**
This commit adds support for PacBSD, a FreeBSD and Arch Linux based OS.  If you can think of a better way to do the package counts let me know and I'll be glad to change it.  The problem is PacBSD has both `pacman` and `pkg` package managers installed by default, but only `pacman` is used.  I had to do the package section the way it is because if `pkg` got called `neofetch` would hang due to `pkg` wanting user input.

This commit also lacks ASCII art because I couldn't find a good way to convert our logo to ASCII, if you have any recommendations on good tools to do so let me know and I'll gladly add it to my PR.

Signed-off-by: Adam Jimerson <vendion@gmail.com>

### CODE REVIEW

**Comment by dylanaraps** [comment]
Thanks for the PR.

Here's my suggestion for the package section, this will also make it easier to add any other BSD distros that use another package manager in the future:

```sh
case "$distro" in
    # PacBSD has both pacman and pkg, but only pacman is used
    "PacBSD"*) packages="$(pacman -Qq --color never | wc -l)" ;;

    *) 
        if type -p pkg_info >/dev/null 2>&1; then
            packages="$(pkg_info | wc -l)"
        elif type -p pkg >/dev/null 2>&1; then
            packages="$(pkg info | wc -l)"
        fi
    ;;
esac
```

For ascii art I turn the distro's logo into a black/white 2 color image like [this](https://ipfs.pics/ipfs/QmcBFAZBCtgroyPuUFaKth4PeCQ7vinXAyhEamwQ4f3Ktu), I then use [this website](http://www.text-image.com/convert/ascii.html) to generate the ascii art. (I don't know if this is the logo you want to use, it's just an example.) The output is something like this:

```sh
                   :+                   
                  .NM:                  
                 `mMMN-                 
                 hMMMMm.                
                sMMMMMMm`               
               +MMMMMMMMd`              
              //+mMMMMMMMh`             
             +MMNhhmMMMMMMh`            
            +MMMMMMMMMMMMMMh`           
           +MMMMMMMMMMMMMMMMh`          
          oMMMMMmsNMMMMMNNMMMd`         
         sMMMMm: ssosymMM.+MMMd`        
        yMMMMM+        --  hMMMm`       
       yMMMMMM/          -yMMMMMm.      
     `hMMMMMMM-         oMMMMMNdNm-     
    `dMMMMMMMMm:       :NMMMMMMMho/     
   .mMMMMMMMMNdy+     .oyhmMMMMMMMNs.   
  -NMMMMds/-`              `./sdMMMMM/  
 -NMdo:`                         -ohMM/ 
-s:`                                `:s:
```

I then edit the ascii art to fit neofetch's format:

```sh
"\
${c1}                   :+
                  .NM:
                 \`mMMN-
                 hMMMMm.
                sMMMMMMm\`
               +MMMMMMMMd\`
              //+mMMMMMMMh\`
             +MMNhhmMMMMMMh\`
            +MMMMMMMMMMMMMMh\`
           +MMMMMMMMMMMMMMMMh\`
          oMMMMMmsNMMMMMNNMMMd\`
         sMMMMm: ssosymMM.+MMMd\`
        yMMMMM+        --  hMMMm\`
       yMMMMMM/          -yMMMMMm.
     \`hMMMMMMM-         oMMMMMNdNm-
    \`dMMMMMMMMm:       :NMMMMMMMho/
   .mMMMMMMMMNdy+     .oyhmMMMMMMMNs.
  -NMMMMds/-\`              \`./sdMMMMM/
 -NMdo:\`                         -ohMM/
-s:\`                                \`:s:
"
```

Finally, the ascii art Inside neofetch:

2016-08-11-174908_738x452_scrot

I hope this helps!

**Comment by vendion** [comment]
I added the image, we can't use the example one you provided due to trademark issues with Arch Linux, but something is off in the formatting as output looks like the following:

2016-08-11-073019_1152x844_scrot

This is what I got when I ran the image through that website (with neofetch formatting applied (wrapped with `"\${c1}"`))

```
"\
${c1}               :+sMs.
             `:ddNMd-                    `   -o--`
            -sMMMMh:  `        `              `+N+``
            yMMMMMs`     `.....-/-...``        `mNh/
            yMMMMMmh+-`:sdmmmmmmMmmmmddy+-``./ddNMMm
            yNMMNMMMMNdyyNNMMMMMMMMMMMMMMMhyshNmMMMm
            :yMMMMMMMMMNdooNMMMMMMMMMMMMMMMMNmy:mMMd
             +MMMMMMMMMmy:sNMMMMMMMMMMMMMMMMMMMmshs-
             :hNMMMMMMN+-+MMMMMMMMMMMMMMMMMMMMMMMs.
            .omysmNNhy/+yNMMMMMMMMMMNMMMMMMMMMNdNNy-
            /hMM:::::/hNMMMMMMMMMMMm/-yNMMMMMMN.mMNh``
           .hMMMMdhdMMMMMMMMMMMMMMmo  `sMMMMMMN mMMm-`
           :dMMMMMMMMMMMMMMMMMMMMMdo+  oMMMMMMN`smMNo`
           /dMMMMMMMMMMMMMMMMMMMMMNd/` :yMMMMMN:-hMMM.
           :dMMMMMMMMMMMMMMMMMMMMMNh`  oMMMMMMNo/dMNN`
           :hMMMMMMMMMMMMMMMMMMMMMMNs--sMMMMMMMNNmy++`
            sNMMMMMMMMMMMMMMMMMMMMMMMmmNMMMMMMNho::o.
            :yMMMMMMMMMMMMMNho+sydNNNNNNNmysso/` -//                      `
             /dMMMMMMMMMMMMMs-  ````````..``    ./:`      /oooo.       -+ooo:`       `/ooo.`
              .oMMMMMMMMMMMMNs`               ./y:`      `MMMMM/`     `+MMMMNy      `hNMMMm:
                +dNMMNMMMMMMMmy`          ``./ys.         omNNm-`      -sNNNh/      `+hNNNo.
                 `/hMMMMMMMMMMMNo-``    `.+yy+-`           ``.`         `````         ``.``
                   `-/hmNMNMMMMMMmmddddhhy/-`                                                 `
                       `-+oooyMMMdsoo+/:. 
"
```

I also worry that may be to wide, is there a prefered image width to use?

**Comment by dylanaraps** [comment]
I use width `40` on the website I linked above.

You have to escape certain chars, see this wiki page for more info:

https://github.com/dylanaraps/neofetch/wiki/Custom-Ascii-art-file-format

Here's the correct logo:

```sh
"\
${c1}      :+sMs.
  \`:ddNMd-                    \`   -o--\`
 -sMMMMh:  \`        \`              \`+N+\`\`
 yMMMMMs\`     \`.....-/-...\`\`        \`mNh/
 yMMMMMmh+-\`:sdmmmmmmMmmmmddy+-\`\`./ddNMMm
 yNMMNMMMMNdyyNNMMMMMMMMMMMMMMMhyshNmMMMm
 :yMMMMMMMMMNdooNMMMMMMMMMMMMMMMMNmy:mMMd
  +MMMMMMMMMmy:sNMMMMMMMMMMMMMMMMMMMmshs-
  :hNMMMMMMN+-+MMMMMMMMMMMMMMMMMMMMMMMs.
 .omysmNNhy/+yNMMMMMMMMMMNMMMMMMMMMNdNNy-
 /hMM:::::/hNMMMMMMMMMMMm/-yNMMMMMMN.mMNh\`\`
.hMMMMdhdMMMMMMMMMMMMMMmo  \`sMMMMMMN mMMm-\`
:dMMMMMMMMMMMMMMMMMMMMMdo+  oMMMMMMN\`smMNo\`
/dMMMMMMMMMMMMMMMMMMMMMNd/\` :yMMMMMN:-hMMM.
:dMMMMMMMMMMMMMMMMMMMMMNh\`  oMMMMMMNo/dMNN\`
:hMMMMMMMMMMMMMMMMMMMMMMNs--sMMMMMMMNNmy++\`
 sNMMMMMMMMMMMMMMMMMMMMMMMmmNMMMMMMNho::o.
 :yMMMMMMMMMMMMMNho+sydNNNNNNNmysso/\` -//                      \`
  /dMMMMMMMMMMMMMs-  \`\`\`\`\`\`\`\`..\`\`    ./:\`      /oooo.       -+ooo:\`       \`/ooo.\`
   .oMMMMMMMMMMMMNs\`               ./y:\`      \`MMMMM/\`     \`+MMMMNy      \`hNMMMm:
     +dNMMNMMMMMMMmy\`          \`\`./ys.         omNNm-\`      -sNNNh/      \`+hNNNo.
      \`/hMMMMMMMMMMMNo-\`\`    \`.+yy+-\`           \`\`.\`         \`\`\`\`\`         \`\`.\`\`
        \`-/hmNMNMMMMMMmmddddhhy/-\`                                                 \`
            \`-+oooyMMMdsoo+/:.
"
```

The logo without the 3 dots fits fine.
```sh
"\
${c1}      :+sMs.
  \`:ddNMd-                    \`   -o--\`
 -sMMMMh:  \`        \`              \`+N+\`\`
 yMMMMMs\`     \`.....-/-...\`\`        \`mNh/
 yMMMMMmh+-\`:sdmmmmmmMmmmmddy+-\`\`./ddNMMm
 yNMMNMMMMNdyyNNMMMMMMMMMMMMMMMhyshNmMMMm
 :yMMMMMMMMMNdooNMMMMMMMMMMMMMMMMNmy:mMMd
  +MMMMMMMMMmy:sNMMMMMMMMMMMMMMMMMMMmshs-
  :hNMMMMMMN+-+MMMMMMMMMMMMMMMMMMMMMMMs.
 .omysmNNhy/+yNMMMMMMMMMMNMMMMMMMMMNdNNy-
 /hMM:::::/hNMMMMMMMMMMMm/-yNMMMMMMN.mMNh\`\`
.hMMMMdhdMMMMMMMMMMMMMMmo  \`sMMMMMMN mMMm-\`
:dMMMMMMMMMMMMMMMMMMMMMdo+  oMMMMMMN\`smMNo\`
/dMMMMMMMMMMMMMMMMMMMMMNd/\` :yMMMMMN:-hMMM.
:dMMMMMMMMMMMMMMMMMMMMMNh\`  oMMMMMMNo/dMNN\`
:hMMMMMMMMMMMMMMMMMMMMMMNs--sMMMMMMMNNmy++\`
 sNMMMMMMMMMMMMMMMMMMMMMMMmmNMMMMMMNho::o.
 :yMMMMMMMMMMMMMNho+sydNNNNNNNmysso/\` -//
  /dMMMMMMMMMMMMMs-  \`\`\`\`\`\`\`\`..\`\`
   .oMMMMMMMMMMMMNs\`               ./y:\`
     +dNMMNMMMMMMMmy\`          \`\`./ys.
      \`/hMMMMMMMMMMMNo-\`\`    \`.+yy+-\`
        \`-/hmNMNMMMMMMmmddddhhy/-\`
            \`-+oooyMMMdsoo+/:.
"
```

**Comment by dylanaraps** [comment]
Also, I'll add the ascii color after this PR.

**Comment by vendion** [comment]
I agree the version without the three dots works better, I also cleaned up a few out of place characters in the image as well.

**Comment by dylanaraps** [comment]
This PR looks good now, let me know when you're ready to merge. :+1:

**Comment by vendion** [comment]
I'm good with merging now.

**Pull request merged**
