### PR TITLE
added /usr/share as a gtk theme directory

### PR DESCRIPTION
**Pull request by iandrewt**
should solve #150

### CODE REVIEW

**Comment by dylanaraps** [comment]
Add the `/usr/` stuff **before** the `/etc/` stuff.

**Comment by iandrewt** [comment]
Fixed. Haven't themed Linux in way too long to have remembered that...

**Comment by dylanaraps** [comment]
All good, I'll merge this once I get home.

**Comment by iandrewt** [comment]
:+1:

**Pull request merged**
