### PR TITLE
[WIP] Added better Ubuntu-GNOME ascii art

### PR DESCRIPTION
**Pull request by hashhar**
Everything's fine apart from the fact that the ASCII is getting too close to the output. I can see a variable called padding in the [source](https://github.com/dylanaraps/neofetch/blob/master/neofetch#L2138) but it doesn't seem like it's being used.

Also, I am trying to add an option for bold ASCII arts. I have a `hack` by changing: `[0-7]) printf "%b%s" "\033[0m\033[3${1}m"` to `[0-7]) printf "%b%s" "\033[1m\033[3${1}m"` on [line 2642](https://github.com/dylanaraps/neofetch/blob/master/neofetch#L2642). But that makes everything bold and hence will not honor settings of a user for not using bold.

**I wanted to ask how are you defining the colors for the ASCII?**

2016-05-14_19-35-15_1366x768

### CODE REVIEW

**Comment by dylanaraps** [comment]
Thanks for the PR, I'm also getting the issue with the logo being too close. 
I'll try and figure out why this is happening.

**Comment by hashhar** [comment]
One thing I've noticed it that most of your logos are 52 characters wide (including the escape codes). Mine is 59. If I make it 52, it looks similar to what the default ones look like. I'll try and see if I can fit it into 52 chars.

**Comment by dylanaraps** [comment]
The padding is dynamic and should work with any width, how did you create this logo?

**Comment by hashhar** [comment]
By hand almost.

**Comment by dylanaraps** [comment]
This issue happens because the `awk` command I'm using to get the length of the longest line for padding outputs an incorrect value. What's weirder is that the issue still occurs when using `wc -L`
to get the length. 

This is an issue with the ascii file itself, we just need to figure out what's causing it.

**Comment by hashhar** [comment]
Hmmm, I think I've used some escapes like "\\`". I'll try using the command on smaller subsections of the ascii and tell you what I find.

**Comment by dylanaraps** [comment]
Yup, I think it's that too. It works in this version without `\` and '`'

```sh
'          ./o.
        .oooooooo
      .oooo```soooo
    .oooo`     `soooo
   .ooo`   .o.   `oooo.
   :ooo   :oooo.   `oooo.
    sooo    `ooooo    ooooo
     oooo    `soooo    `ooooo
      `soooo    `oooo    `soooo
./oo    `oooo    `oooo.   `ooo
`oooo.   `oooo.   `oooo.   ``
  `oooo.    oooo     ooo`
     `ooooo    ``    .oooo
       `soooo.     .oooo`
         `ooooooooooo`
            ``ooo``
'
```

**Comment by hashhar** [comment]
Oh, then it's just a matter of removing them?

**Comment by dylanaraps** [comment]
Ok, this is actually a neofetch issue. Adding `ascii_strip=${ascii_strip//\\\\/ }` to line `2131` fixes the issue. I just tested with all 64 distro logos and it doesn't cause any issues.

The resoluting block should look like this:

```sh
    # Turn the file into a variable and strip escape codes.
    ascii_strip=$(<"$ascii")
    ascii_strip=${ascii_strip//\$\{??\}}
    ascii_strip=${ascii_strip//\\\\/ }
    ascii_strip=${ascii_strip//\\}
```

**Comment by hashhar** [comment]
Okay. So do you want me to add it, or it would be added on master by you.

**Comment by dylanaraps** [comment]
I'll push it to master now.

**Comment by dylanaraps** [comment]
Done.

**Comment by dylanaraps** [comment]
Also in your ascii logo there's a 1 space gap on the left side, are you able to remove it for consistency with the other logos?

**Comment by hashhar** [comment]
Sure.

**Comment by dylanaraps** [comment]
Thanks, I also just pushed bold ascii to master.

You can enable it by setting `$ascii_bold` to `on` or by using `neofetch --ascii_bold on`.

**Comment by dylanaraps** [comment]
Is this ready to be merged? LGTM

**Comment by hashhar** [comment]
LGTM. Thanks for the bold option.

**Comment by dylanaraps** [comment]
No problem. :)

**Pull request merged**
